language: scala
scala:
  - 2.10.4
before_install:
  - sudo apt-get install zookeeperd
  - sudo apt-get install zookeeper-bin
  - sudo /usr/share/zookeeper/bin/zkServer.sh start
  - sudo /usr/share/zookeeper/bin/zkServer.sh status
